name: "starter"
version: "0.0.8"
usage: "helm starter generate"
description: |-
  Helm plugin designed to generate the files required for CI/CD
ignoreFlags: false
useTunnel: false
command: "make -f $HELM_PLUGIN_DIR/Makefile"

