name: "pipeline"
version: "0.1.0"
usage: "helm pipeline generate"
description: |-
  Helm plugin designed to generate the files required for CI/CD
ignoreFlags: false
useTunnel: false
command: "make -f $HELM_PLUGIN_DIR/Makefile"

